name: "Setup bolt cli"
description: "Installs and configures the bolt cli"

runs:
  using: "composite"
  steps:
    - name: "Setup Rust environment"
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - run: ${{ github.action_path}}/configure.sh
      shell: bash

    - name: "Configure bolt"
      shell: bash
      run: |
        echo MSG="${{ github.event.head_commit.message }}" | grep -oP '(?<=\()[^\)]+'

        TARGET="$(echo MSG="${{ github.event.head_commit.message }}" | grep -oP '(?<=\()[^\)]+')"

        export TARGET
