name: "Setup bolt cli"
description: "Installs and configures the bolt cli"

outputs:
  TARGET:
    description: "Returns the name of the repo which has been changed"
    value: ${{steps.output-generator.outputs.target}}

runs:
  using: "composite"
  steps:
    - name: "Setup Rust environment"
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: "Install bolt"
      shell: bash
      run: cargo install bolt-cli

    - id: output-generator
      shell: bash
      run: |
        echo "::set-output name=target::$(echo MSG="${{ github.event.head_commit.message }}" | grep -oP '(?<=\()[^\)]+')"
